### ISSUE TITLE
Recipe-app: Kanban_review

### ISSUE THREAD

**Issue by Juanpa8830** [Juanpa8830/recipe-app#12]
# hello reviewer.
## We hope you are having a great day, any suggestion will be welcome, thank you very much for the support 😄 🌴

- this is the link to our priject-issues: https://github.com/Juanpa8830/recipe-app/issues
- Our team is conformed by two people:
 

@PierreBarba , @Juanpa8830 

- we already applied the requested changes:

1. Add missing columns:

![image](https://user-images.githubusercontent.com/113477568/234063567-4dedbb19-546c-450e-86d5-40fa17a31998.png)

2. You can check the link again and it is now referring to the issues page.
3. Please let us know if you can see the changes applied because our project was private and now it is public, so you should be able to check it in detail.

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on, but you are almost there! 
🏁  🌴 🚦 🚗 🏫  🏡   _🏃 🏃  🌴 🌴 

## Highlights 👍  
- Tasks distributed fairly!

## Required Changes ♻️
- [x] Like in the previous boards, kindly ensure that the following columns are added to the board:
  * To Do
  * In Progress
  * In Review
  * Done

- [x] Few of your cards do not have description. Kindly ensure add description to this card appropriately.

**No description provided:**
![image](https://user-images.githubusercontent.com/12745474/234053649-031746fd-bd0a-423e-b37f-2080cf034837.png)

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Juanpa8830** [comment]
Hi @rloterh 

We already applied the requested changes.

Thank you so much for your feedback!

**Comment by addod19** [comment]
### Hi @Juanpa8830 and @PierreBarba, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Nice job with this project :man_technologist: 

 ## Required Changes ♻️
_Check the comments under the review._
- [x] As mentioned in the previous review, this part of the comment was not addressed, there are columns missing. Kindly fix it
![Screenshot from 2023-04-24 16-37-22](https://user-images.githubusercontent.com/46388113/234059365-0f9e1b9c-c79c-4f73-bb2f-6686755c7fa8.png)
- [x] Also, instead of adding the link to the GitHub repo, we are required to add the link to the GitHub issues page. I had to manually search for it which should be the case. The Kanban board isn't created the right way
![Screenshot from 2023-04-24 16-42-40](https://user-images.githubusercontent.com/46388113/234060555-ac4e422e-652c-421f-93af-e9ba21b440cc.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Owusu-Desmond** [comment]
Hi @Juanpa8830 and @PierreBarba , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/SmoCFhZCi1kzu/giphy.gif"/>

## Highlights
📌 Great working on the setup of the project board ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
